BASE:
  exp_id: 1
  seed: 28
  gpu: "0"
  save_epochs: [270, 290, 305, 320, 330, 345, 350]

ACTIVE:
  strategie: random  # selection strategies
  k: 5

TRAINING:
  pretrain:
  batchsize: 4
  accu_iter: 1  # accumulate gradient
  normalize_color: True
  optimizer: SGD  # choice [SGD, Adam]
  lr: 1e-1
  weight_decay: 1e-4
  adam_beta1: 0.9    # for adam optimizer
  adam_beta2: 0.999  # for adam optimizer
  momentum: 0.9  # for sgd optimizer
  dampening: 0.1 # for sgd optimizer
  lr_schedule: PolyLR  # choice [StepLR, PolyLR, SquaredLR]
  step_size: 2e4 # steplr
  step_gamma: 0.1 # steplr
  max_iter: 100000  # polylr
  poly_power: 0.9 # polylr
  eval_epochs: 5  # evaluate model frequency

DATA:
  data_root: PATH_TO_SCANNET_DATA
  val_data_root: PATH_TO_SCANNET_VAL
  segment_root: PATH_TO_SCANNET_OVERSEGMENT
  propagate_label: True
  voxel_size: 0.02
  ignore_label: -100
  num_workers: 20


AUGMENTATION:
  # coords
  elastic_distortion: True
  ELASTIC_DISTORT_PARAMS: [ [ 0.2, 0.4 ], [ 0.8, 1.6 ] ]
  random_scale: True
  SCALE_AUGMENTATION_BOUND: [ 0.9, 1.1 ]
  random_rotation: True
  ROTATION_AUGMENTATION_BOUND: [ [ -0.0490625, 0.0490625 ], [ -0.0490625, 0.0490625 ], [ -3.14, 3.14 ] ]
  random_flip: True
  ROTATION_AXIS: z
  random_dropout: True
  dropout_ratio: 0.2
  # color
  chromaticautocontrast: True
  chromatictranslation: True
  data_aug_color_trans_ratio: 0.1
  chromaticjitter: True
  data_aug_color_jitter_std: 0.05
